### PR TITLE
Remove the properties related to Redphone and WebRTC support.

### PR DESCRIPTION
**Pull request by charlesmchen**
PTAL @michaelkirk

### CODE REVIEW

**Comment by charlesmchen** [comment]
Not for v2.10.

**Review by michaelkirk — APPROVED** [review]
LGTM pending confirmation that other clients don't use these fields.

**Comment by charlesmchen** [comment]
Per Moxie, we're not going to merge this until we tear down the RedPhone infrastructure.

**Comment by michaelkirk** [comment]
>> LGTM pending confirmation that other clients don't use these fields.
> Per Moxie, we're not going to merge this until we tear down the RedPhone infrastructure.

You know what, that was my bad. This PR is just affecting what we're storing locally for other recipients - not what we're sending the accounts API, where we've already hardcoded those fields to be YES: https://github.com/WhisperSystems/SignalServiceKit/blob/master/src/Account/TSAttributes.m

I think we can merge this post haste. Right?

**Pull request merged**
