### PR TITLE
Fix broken tests.

### PR DESCRIPTION
**Pull request by charlesmchen**
PTAL @michaelkirk

### CODE REVIEW

**Comment by charlesmchen** [comment]
See: https://github.com/WhisperSystems/Signal-iOS/pull/2266

**Review by michaelkirk — COMMENTED** [review]
There are a lot of singleton asserts in the code base. I think we should solve this within the assert so we don't have to add something like this to every class.

e.g. see my existing PR: https://github.com/WhisperSystems/SignalServiceKit/pull/244

Or convert them all to protocols 😬

**Comment by charlesmchen** [comment]
Interesting, let's talk on your PR.

**Comment by michaelkirk** [comment]
Closing as I think #244 took care of everything. LMK if I missed something.

**Pull request closed without merging**
